### ISSUE TITLE
Why raw.Charts.Definitions is slice of Definition?

### ISSUE THREAD

**Issue by Wing924** [l2isbad/go.d.plugin#10]
Python plugin use dict type. Why go plugin use slice?

If we use `raw.Charts.Definitions` as slice, we don't need `raw.Charts.Order` because slice is ordered.
If we use`raw.Charts.Definitions` as map, we need `raw.Charts.Order` to show the chart order.

**Comment by l2isbad** [comment]
The main idea is to have same interface for user charts as `python.d.plugin` provide.
Plus `Order` is nice because it's on the top of charts and it's clear how many what charts. **Easy to see/change order.** (which is huge).

Other than this there are no other reasons.

Technically it's not needed, yes. But i think `Order` is nice to have.

**Comment by Wing924** [comment]
How about make `raw.Charts.Definitions` `map[string]Definition` ?

**Comment by l2isbad** [comment]
That means we will need move chart `ID` to map `key` which is ugly (or duplicate chart id, which is ugly too).

Other then that - slices are nice, maps values are not addressable, which means you forced to map[string]*Type. Slices values (`slice[index]`) always addressable.

One of my todo is to replace some maps with slices in cooked charts.

**Comment by l2isbad** [comment]
I suggest to leave it as is.

**Comment by Wing924** [comment]
It's not a big problem. We can keep as is and discuss it later.

But I suggest change it to map like what python plugin doing.

**Comment by l2isbad** [comment]
Ok, back to this

`Definitions map[string]*Chart` (must be `*Type`)

```go
var charts = Charts{
	Order: Order{"response_time", "response_length"},
	Definitions: Definitions{
		"response_time": &Chart{
			ID:      "response_time",
			Options: Options{"HTTP Response Time", "ms", "response"},
			Dimensions: Dimensions{
				Dimension{"response_time", "time", "", 1, 1e6},
			},
		},
		"response_length": &Chart{
			ID:      "response_length",
			Options: Options{"HTTP Response Body Length", "characters", "response"},
			Dimensions: Dimensions{
				Dimension{"response_length", "length"},
			},
		},
	},
}
```

Looks super bad imo (duplicate dim id + reference to chart).
To be honest that's was the first implementation :smile: Then i switched to slice of Charts. FeelsGoodMan after that :smile:

**Comment by Wing924** [comment]
Yes, this looks bad. Let's keep as is (slice version).

**Comment by l2isbad** [comment]
Are you happy with `Definitions []*Chart` ? :smile: If so please close the issue
