### ISSUE TITLE
NewXXX shoud be pointer of XXX

### ISSUE THREAD

**Issue by Wing924** [l2isbad/go.d.plugin#11]
https://github.com/l2isbad/go.d.plugin/blob/cc2db8145867b61054d686449b038837508ac414/internal/pkg/charts/raw/chart.go#L29

<https://golang.org/doc/effective_go.html#package-names>

Go don't have constructor, we use `NewXXX(...)` and `New(...)` as constructor.
We expect constructor return a pointer, not value.
Let's change it to `*Chart`

**Comment by l2isbad** [comment]
> We expect constructor return a pointer, not value.

I feel it was the reason i did in that way. Don't remember why now :smile: 
Give me some time, i will check it later (later today or even yesterday, will be very busy today)

**Comment by l2isbad** [comment]
@Wing924
According specs there is nothing wrong to return a value (not ptr) from constructor. It depends.

Btw keep in mind that when a reference is returned, a value is created on heap (`malloc`) - more work for GC.

Summarizing the above - constructor should return ptr only if ptr value makes more sense.

**Comment by Wing924** [comment]
Since `new(...)` return a ptr, we expect `NewXXX(...)` also return a ptr.
You can check the standard library and found all `NewXXX(...)` return a ptr (Correct me if I'm arong. I don't check all, just simple grep check).

> Btw keep in mind that when a reference is returned, a value is created on heap (malloc) - more work for GC.

It's not a problem unless we face a performance issue. We should forget about small efficiencies, say about 97% of the time: premature optimization is the root of all evil.

**Comment by l2isbad** [comment]
> Since new(...) return a ptr, we expect NewXXX(...) also return a ptr.

1. Who we? :smile: 
2. Not sure about connection between the two.

`new()` returns pointer to a newly allocated zero value of Type.
Do you expect ptr **to a newly allocated zero value** from NewXXX() ?

I am not against returning ptr from constructor! I'm just saying that there is no idiom/rule about that. 
Constructor can return interface whose dynamic type is not a ptr ([example](https://github.com/l2isbad/go.d.plugin/blob/master/internal/modules/web_log/matcher/matcher.go#L12-L34))

**Comment by Wing924** [comment]
I post this issue because:
* Standard Library use `NewXXX(...) *XXX`, even though no explicit idiom/rule.
* `raw.Chart` has many methods with pointer receiver.
  * [returning value vs pointer in Go constructor](https://stackoverflow.com/questions/32208363/returning-value-vs-pointer-in-go-constructor)

**Comment by l2isbad** [comment]
> Standard Library use NewXXX(...) *XXX, even though no explicit idiom/rule.

I agree that it **make sense**, `New()` creates value and return ptr to this value (copy of ptr).

Currently `NewChart()` creates value and returns copy of created value (return == copy)

**Comment by l2isbad** [comment]
> raw.Chart has many methods with pointer receiver.

The reason is my laziness. Have to be fixed. I think we should use ptr rec method only if it's really needed.

**Comment by Wing924** [comment]
Btw, if the receiver is value, call method = copy that value.

**Comment by l2isbad** [comment]
It's always copy in `go`, the question is what do you want to copy, ptr or value :smile:

**Comment by l2isbad** [comment]
@Wing924 you were absolutely right. I made a lot of changes.

Changes:

1. `raw.NewChart()` returns `*raw.Chart`
2. `raw.Chart.AddDimm(), raw.Chart.AddDimm()` expects `*raw.Chart`
3. 1 + 2 = raw.Definitions is []*raw.Chart

**Comment by l2isbad** [comment]
i will concentrate on the charts packages for the next few days. I want them be stable and without bugs. So more changes are coming :smile: 

nice catch @Wing924

**Comment by l2isbad** [comment]
i will open an issue to discuss changes
