### ISSUE TITLE
cooked package objects structure

### ISSUE THREAD

**Issue by l2isbad** [l2isbad/go.d.plugin#14]
**charts** current implementation:

```go
type charts struct {
	charts   map[string]*Chart 
	bc       baseConfHook
	priority int
}
```

I suggest to change to

```go
type charts struct {
	charts  []*Chart  // !! changes
	bc       baseConfHook
	priority int
}
```

**chart** current implementation:
```go
type (
	Chart struct {
        ....
	}
	dimensions []*dimension
	variables  map[string]*variable
)
```

I suggest to change to

```go
type (
	Chart struct {
        ....
	}
	dimensions []*dimension
	variables  []*variable // !! changes
)
```

Feels more natural to me. Duck maps. What do you think @Wing924 ?

**Comment by Wing924** [comment]
> `charts  []*Chart  // !! changes`

Could you tell me the reason?
I think map is more natural. If you change it to list, you need to linear search.
```go
// GetCharts returns chart by id.
func (c *charts) GetChartByID(id string) *Chart {
	return c.charts[id]
}

// LookupChartsByID looks up a chart by id.
func (c *charts) LookupChartByID(id string) (*Chart, bool) {
	v, ok := c.charts[id]
	return v, ok
}
```

**Comment by l2isbad** [comment]
?
```go
type charts struct {
	chartsMap   map[string]*Chart  // items?
	bc       baseConfHook
	priority int
}
```

**Comment by Wing924** [comment]
how about this?
```go
type charts struct {
	items   map[string]*Chart  // items?
	bc       baseConfHook
	priority int
}
```

**Comment by l2isbad** [comment]
This should definitely be `items`, yes.

**Comment by l2isbad** [comment]
off topic:

https://github.com/l2isbad/go.d.plugin/blob/453946b8c002e579c8aefad9547bc57ada1e4289/internal/pkg/helpers/web/request.go#L23-L29

After adding a `CreateHTTPClient` function i think we don't need `CreateHTTPClient` method. 
?

**Comment by Wing924** [comment]
yes, we can delete`func CreateRequest(r *Request) (*http.Request, error)`.

**Comment by l2isbad** [comment]
https://github.com/l2isbad/go.d.plugin/blob/453946b8c002e579c8aefad9547bc57ada1e4289/internal/pkg/helpers/web/client.go#L24-L27

Why ptr receiver?

**Comment by Wing924** [comment]
> Why ptr receiver?

no reason, just copied from your code.
`func CreateHttpClient(c *Client) *http.Client`

**Comment by l2isbad** [comment]
Ok, summary:
1. `items   map[string]*Chart` is ok.

> If you change it to list, you need to linear search.

Is a good point. You are right.

2. `variables  map[string]*variable`

I don't see any reason to use map here, i will change it to `[]*variable`

**Comment by Wing924** [comment]
You wrote this method, but it's never be called.
If you don't need this mehod, change to `[]*variable` is OK.
```go
// GetVarByID returns variable by id.
func (c *Chart) GetVarByID(varID string) *variable {
	return c.variables[varID]
}
```
