### ISSUE TITLE
Refactor Plugin/Job

### ISSUE THREAD

**Issue by Wing924** [l2isbad/go.d.plugin#19]
Currently, GoDPlugin and job part are very complex and hard to read.
I'm doing something refactor now.

My goal:

- [ ]  The main should be responsible for args and ENV.
- [ ]  The GoDPlugin should be responsible for controlling jobs and global time tick.
- [ ] The jobs should be responsible for doing real tasks.

**Comment by l2isbad** [comment]
Hm, `GoDPlugin ` is not complex at all, it has only 4 steps - `create`, `init`, `check` and `start` job.  I found it very easy.

**Comment by Wing924** [comment]
Try to write unit tests and you will find how complex they are.

**Comment by l2isbad** [comment]
Wy `global time tick` when every job kinda has their own uppdate freq?

**Comment by Wing924** [comment]
global time ticker is easier to sync time.
we expect all modules run at the time and if a module run longer than 1sec, it shoud skip next run, right?

**Comment by l2isbad** [comment]
> we expect all modules run at the time and if a module run longer than 1sec, it shoud skip next run, right?

No and no.

**Comment by l2isbad** [comment]
> global time ticker is easier to sync time.

There is nothing to sync. Do a run, and calc the next based on spent time.

**Comment by Wing924** [comment]
what will happen if a module run more than 1sec?

**Comment by Wing924** [comment]
https://play.golang.org/p/L4CzszOHxrX

This example shows how easy to use global clock with chan.

**Comment by l2isbad** [comment]
i agree that chan's, tickers is go way, but keep in mind - evey job (not module) has its own update freq, data collections must be aligned to seconds boundaries. I have no clue if std Ticker provide that functionality (it should tick at 00:01, 00:02, not at 00.01:010, 00.02:010)

**Comment by Wing924** [comment]
> data collections must be aligned to seconds boundaries

I'll check it.

**Comment by l2isbad** [comment]
Read [this article](https://github.com/firehol/netdata/wiki/External-Plugins#writing-plugins-properly) carefully . So i basically implement Costa's `The best way to iterate at a constant pace is this pseudo code:`.

**Comment by l2isbad** [comment]
The most important:

1. We must make sure we are always aligned with the netdata daemon. Mandatory.  **Accurately** calculate time for the next run. We have to use monotonic here.
2. We have to **accurately** calculate`time passed since the last run`. Calculate it using real time, not monotonic. Mandatory.

**Comment by l2isbad** [comment]
It's default values per module (per module, not per job).

https://github.com/l2isbad/go.d.plugin/blob/3603bb5e80d6f19cb7658c343d28603b5b059275/internal/modules/example/example.go#L35

**Comment by Wing924** [comment]
Understood.
Please don't make name too short or unable to read.

**Comment by l2isbad** [comment]
Oh, `S` means setter, `G` means getter.

**Comment by Wing924** [comment]
The defaults part looks like a very hack way.
I want to change it to standard method like `UpdateEvery`

AS IS:
```go
type Module interface {
	...
	SetLogger(l *logger.Logger)
	UpdateEvery() int
	SetUpdateEvery(v int)
	ModuleName() string
	SetModuleName(v string)
}
```

TO BE:
```go
type Module interface {
	...
	SetLogger(l *logger.Logger)
	UpdateEvery() int
	SetUpdateEvery(v int)
	ModuleName() string
	SetModuleName(v string)
+     RequireConfig() bool // alternative of NoConfiger
+     DefaultUpdateEvery() int
+     DefaultChartsCleanup() int
+     DisabledByDefault() bool
}
```

**Comment by l2isbad** [comment]
> The defaults part looks like a very hack way.

I don't think so. **I like that all defaults in `init`.**


> +     RequireConfig() bool // alternative of NoConfiger

:+1:

**Comment by Wing924** [comment]
> I don't think so. I like that all defaults in init.

It's really hack and hard to understand.

**Comment by Wing924** [comment]
```go
func init() {
       // if you a new developer, how do you know this line will apply to this module only or all modules?
	modules.SetDefault().SetDisabledByDefault()

	f := func() modules.Module {
		return &Example{
			data: make(map[string]int64),
		}
	}
	modules.Add(f)
}
```
VS

```go
func (e *example) DisabledByDefault() bool { return true }
func init() {
	f := func() modules.Module {
		return &Example{
			data: make(map[string]int64),
		}
	}
	modules.Add(f)
}
```

**Comment by l2isbad** [comment]
Ok ok, then add defaults right before `init`  should be a rule.

**Comment by Wing924** [comment]
@l2isbad I found a better way to describe default module values. How do you think?

AS IS:
```go
type Creator func() Module

func init() {
	modules.SetDefault().SetDisabledByDefault()

	f := func() modules.Module {
		return &Example{
			data: make(map[string]int64),
		}
	}
	modules.Add(f)
}
```
TO BE:
```go
type Creator struct {
		UpdateEvery       int
		ChartCleanup      int
		DisabledByDefault bool
		NoConfig          bool
		Create            func() Module
	}

func init() {
	modules.Add(modules.Creator{
		DisabledByDefault: true,
		Create: func() modules.Module {
			return &Example{
				data: make(map[string]int64),
			}
		},
	})
}
```

**Comment by l2isbad** [comment]
`ChartCleanup` 0 is a valid value, how should we distinguish between zero and default values? And we can add one more option later wich zero value != default value.

**Comment by Wing924** [comment]
How about this?
`const ChartCleanupNever = 3600*24*365*1000` // large enough value
if `ChartCleanup` is `0`, we treat it as default value(`10`)
if you want to disable it, set `ChartCleanupNever`

**Comment by l2isbad** [comment]
> if ChartCleanup is 0, we treat it as default value(10)

Looks hacky :smile: `ChartCleanup 0` is 0, not 10 or whatever. 
To be honest i want `Creator` to stay a func.

**Comment by Wing924** [comment]
Why I want to make this change is that we can't get value before we create the module but we want to get DisabledByDefault in advance.

How about ptr way?
```
ChartCleanup      *int // <- ptr here
```

**Comment by l2isbad** [comment]
> Almost no problem if don't mind the extra module instance

I think it is no problem at all

**Comment by l2isbad** [comment]
```go
type Module interface {
	...
	SetLogger(l *logger.Logger)
	UpdateEvery() int
	SetUpdateEvery(v int)
	ModuleName() string
	SetModuleName(v string)
+     RequireConfig() bool // alternative of NoConfiger
+     DefaultUpdateEvery() int
+     DefaultChartsCleanup() int
+     DisabledByDefault() bool
}
```

btw then we need `RequireRecover` instead of `Unsafer`

**Comment by Wing924** [comment]
I think keep Creator func is acceptable, but change it to struct is better.

Don't you think it more natural?
```go
// create job
conf := job.NewConfig()
	conf.RealModuleName = moduleName
	conf.UpdateEvery = p.Option.UpdateEvery
	if creator.UpdateEvery != nil {
		conf.UpdateEvery = *creator.UpdateEvery
	}
	if creator.ChartCleanup != nil {
		conf.ChartCleanup = *creator.ChartCleanup
	}
```

**Comment by Wing924** [comment]
> btw then we need RequireRecover instead of Unsafer

I checked teregraf, it treat all plugin as unsafe.
Why don't we do the same?

**Comment by l2isbad** [comment]
> Why don't we do the same?

Ha, indeed. Why not. Shut them in case of `panic` ?

**Comment by Wing924** [comment]
Yes

**Comment by l2isbad** [comment]
> Don't you think it more natural?

Looks messy a bit, don't you think so?
```go
func init() {
       u = new(int)
       *u = 5
	modules.Add(modules.Creator{
                UpdateEvery: u,
		DisabledByDefault: true,
		Create: func() modules.Module {
			return &Example{
				data: make(map[string]int64),
			}
		},
	})
}
```

**Comment by Wing924** [comment]
> Looks messy a bit, don't you think so?

Yes, I agree, but acceptable because only a few modules need to change the default value.

But now I encounter another problem which make `DefaultUpdateEvery()` way unacceptable:
if `DefaultUpdateEvery()` returns `1`, how to distinguish it's the default value or  module specific value?

**Comment by Wing924** [comment]
It can be a little simple:
```go
func init() {
       u := 5
	modules.Add(modules.Creator{
                UpdateEvery: &u,
		DisabledByDefault: true,
		Create: func() modules.Module {
			return &Example{
				data: make(map[string]int64),
			}
		},
	})
}
```

**Comment by l2isbad** [comment]
Ok, then lets do ptr for all numeric default options
