### ISSUE TITLE
[web_log] string match vs regexp match

### ISSUE THREAD

**Issue by l2isbad** [l2isbad/go.d.plugin#2]
Python version uses additional **regexp** searches for (**in addition to 2 mandatory searches for every row**):
1. `filter` feature. Up to +2 searches (include, exclude)
2. `requests per category` feature. Up to +N searches (number of categories).

Bad regexp can drammaticaly slow down the whole plugin (python one). 

```python
import re
import time

r = re.compile('.*MISS.*')

row = '10.6.1.213 - - [15/Apr/2018:07:56:34 +0900] "OPTIONS cacti HTTP/1.1" 200 29 490 0.001 0.001 "health.whatever.whatever" "-" "Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0'

s = time.time()
for i in range(100000):
    #'MISS' in row
    r.search(row)
print(time.time() - s)

```
**regexp time**: `3.2602620124816895`
**string match time** : `0.01069951057434082`

**Imo in most cases string match is enough for both features**. String match is much faster.

```yaml
categories:
    cat1: 'qwerty'
    cat2: 'ytrewq'
```

The question is when we should use string match and when regexp.

1. default is regexp, string if it's clearly indicated (example: value is prepended with `s:`)
```yaml
categories:
    cat1: 's:qwerty'
```

2. opposite to the first (example: value is prepended with `re:`)
```yaml
categories:
    cat1: 're:qwerty'
```
3. make a decision based on checking the characters in the string
4. ?

@ktsaou @Ferroin

**Comment by Ferroin** [comment]
Hmm... Does our YAML parser properly support mappings that look like this?

    categories:
        cat1: regex='something'

If so, that's what I would personally suggest.  You can then have a check that there is exactly one item in the `cat1` mapping, and use the key for that item to determine what type of matching is needed.  This would be consistent with a number of the other big projects that I've seen which use YAML (see for example [Ansible](https://github.com/ansible/ansible)), and it gives the option of adding other search types in the future (if for example we decide to add a new regex library, or allow a separate hook for prefix searches (those should be even faster than substring searches, though they're probably not as useful)).

**Comment by l2isbad** [comment]
This will break old interface :smile_cat:  Currently configs for both versions are the same.

**Comment by Ferroin** [comment]
The old interface assumes a simple substring match, correct?  If so, just make it so that lack of the key='value' structure behaves like the old interface, and make this a special case.  That _may_ still break someone's config, but it would leave a majority of the working correctly (and if you're going to break something, now would be the time to do it).

**Comment by ktsaou** [comment]
I need exactly the same abbreviation for simple patterns. I want them to support regex too. So, I think we should use the same syntax.

I tried to find what others are doing.

Generally, there are: https://en.wikipedia.org/wiki/Regular_expression#Standards

1. POSIX basic regular expressions (BRE)
2. POSIX extended regular expressions (ERE)
3. POSIX Simple Regular Expressions (SRE)
4. Perl Compatible Regular Expressions (PCRE)

The `find` command states a few more: 

```sh
# find -regextype help
find: Unknown regular expression type ‘help’; valid types are ‘findutils-default’, ‘awk’, ‘egrep’, ‘ed’, ‘emacs’, ‘gnu-awk’, ‘grep’, ‘posix-awk’, ‘posix-basic’, ‘posix-egrep’, ‘posix-extended’, ‘posix-minimal-basic’, ‘sed’.
```

I understand we should use some kind of prefix to let the user pick one among the ones we support. I have seen references with `r'regex string'` and `p'regex string'`, but I am not sure how to pick them. It needs some more research...

**Comment by l2isbad** [comment]
> I suggest use substring match as default.

That's my thoughts too. As i said in my first post - string match is enough for `filter/categories` feature. @ktsaou i know you are using `filter/categories` a lot. Can it be replaced by string match (string contains) in your case? 

But to support transparent migration from `python` to `go` version, we need to leave regex search method as default :cry:

**Comment by Wing924** [comment]
@l2isbad 
How about check the pattern string? If it doesn't contain special char, treat it as substring match.

* abc => `strings.Contains(...)`
* ^abc => `strings. HasPrefix(...)`
* abc$ => `strings. HasSuffix(...)`
* others => regexp

**Comment by l2isbad** [comment]
> How about check the pattern string?

I was thinking about it, and google a lot for such implementation. Unsuccessful :cry:  There is no way to check if this a string or regexp (actually regexp is a string). 

> ^abc => strings. HasPrefix(...)
> abc$ => strings. HasSuffix(...)

This is not useful for `web_log` `filter/categories`.

The best idea is let to user to decide which search method he needs.

**Comment by l2isbad** [comment]
Still i don't like that regex is default.

**Comment by Wing924** [comment]
> This is not useful for web_log filter/categories.

I give you a real filter/categories example for my servers:
```yaml
categories:
  healthcheck: ^/-/healthy
  static: ^/static/
  php: .php$
```

In my case, I don't need regexp. What I need is substring match and prefix/suffix match.

**Comment by Wing924** [comment]
> There is no way to check if this a string or regexp

We don't need complete thing. Just a simple logic is OK.
```go
func IsRegExp(s string) bool {
    if regexp.QuoteMeta(s) == s {
        return true
    }
    return false
}
```

**Comment by l2isbad** [comment]
So your config will be

```yaml
categories:
  healthcheck: string=^/-/healthy
  static: string=^/static/
  php: string=.php$
```

Other optimization will be done by the string matcher (`^abc => strings. HasPrefix(...), abc$ => strings. HasSuffix(...)`).

**Comment by l2isbad** [comment]
```go
regexp.QuoteMeta("^/-/healthy") != "^/-/healthy"
```

Still i think we must leave this to the user. It's ok. @ktsaou @Ferroin

**Comment by l2isbad** [comment]
"string prefix", "string suffix" match for `string matcher` optimization implemented.

**Comment by Ferroin** [comment]
@ktsaou Realistically, just supporting one really expressive regex format should be sufficient.   Either PCRE, Python `re` module (not actually PCRE, they have a lot of similarities, but are not the same thing by any means), or Vi-style (which, IIRC, is _mostly_ the same as `sed`, which in turn is mostly a POSIX ERE syntax) would be my preference.  Vi-style is going to likely be a bit easier on sysadmins who are not programmers, but PCRE and Python style are more expressive.  [re2](https://github.com/google/re2) might also be a decent option, there are Python bindings and it's the same syntax that the Go `regexp` module uses.

@l2isbad I'm not quite certain what you mean by 'leave this to the user'.  DO you mean leaving the decision of whether or not something is a regex?

**Comment by l2isbad** [comment]
@Wing924 suggested [to make a decision based on characters in the string ](https://github.com/l2isbad/go.d.plugin/issues/2#issuecomment-406931061)

I said that this not the best solution and it will lead to errors.

Much easier is let the user to decide which search method he needs. Why not? 

```yaml
regex=REGULAR_EXPR
string=STRING_TO_MATCH
```

If `search_method=value` structure is not met - no go, log error, skip job.

**Comment by Ferroin** [comment]
OK, that makes sense, and I agree that it's a lot easier to just have the user select what matching method to use (especially for the user, because they can immediately tell what search method is going to be used).

For compatibility reasons though, it might be worthwhile to treat matches without the `search_method='value'` structure however the current `web_log` module handles them (it's a substring search right now isn't it?).   That would make it somewhat easier for people converting from the old module to the new one.

**Comment by l2isbad** [comment]
> however the current web_log module handles them

`web_log` uses regex searches for all (see 1 post). It can be 10+ regex searches per row :smile: 

**That is the reason why i highlighting this problem**

I think we should break old stuff and notify the user of new features. And only if he decides continue to use regexes he will have to rewrite config.

**Comment by l2isbad** [comment]
I mean user have to decide to use regex searches, not we.

**Comment by Ferroin** [comment]
OK, that makes sense then.

**Comment by l2isbad** [comment]
agreed on `search_method=value`
