### ISSUE TITLE
Go getter/setter naming rule

### ISSUE THREAD

**Issue by Wing924** [l2isbad/go.d.plugin#4]
> Go doesn't provide automatic support for getters and setters. There's nothing wrong with providing getters and setters yourself, and it's often appropriate to do so, but it's neither idiomatic nor necessary to put Get into the getter's name. If you have a field called owner (lower case, unexported), the getter method should be called **Owner (upper case, exported), not GetOwner**. The use of upper-case names for export provides the hook to discriminate the field from the method. A setter function, if needed, will likely be called SetOwner.

<https://golang.org/doc/effective_go.html#Getters>

I found you use GetXXX for getter. This is not general in Go.
ex. https://github.com/l2isbad/go.d.plugin/blob/master/internal/modules/module.go#L26

**Comment by l2isbad** [comment]
Yeah, i used them a lot.
In general i agree, doing getters i felt it's wrong.. :smile: 

I will fix it.

**Comment by Wing924** [comment]
If you don't mind, I'll send refactor PR.

**Comment by l2isbad** [comment]
Already do some changes. 

> If you don't mind, I'll send refactor PR.

you are welcome, but update to current master first

**Comment by l2isbad** [comment]
@Wing924 good thing about `Get..` i like - easy to see all getters by writing `obj.Get` in IDE.

**Comment by Wing924** [comment]
Yes, I know that. My Java codes are full of `GetXXX`. I don't know why but Go choose not to use`GetXXX`.
Maybe many people don't use IDE? (I use VS code or vim)

**Comment by l2isbad** [comment]
btw about `GetCharts()` from `Charts interface`. I think we should replace it with `List() []string`.
What do you think?

**Comment by Wing924** [comment]
I think you're talking about here:
https://github.com/l2isbad/go.d.plugin/blob/6a377df14c8050055bc32b57d9aa32589eb4c8b9/internal/modules/module.go#L23-L29

If you want to get list of names, I think `ListNames() []string` or `GetNames() []string` are better.

I'm just starting reading the code, why you want to replace `GetCharts` with list name? It looks much different.

Btw, in my personal opinion, a plural name like `Charts` refers to list of singular one.
ex.
```go
type(
    Chart struct{...}
    Charts []Chart
)
```

**Comment by Wing924** [comment]
LGTM!

**Comment by l2isbad** [comment]
@Wing924 i really appreciate your help :+1: now things will go faster

**Comment by l2isbad** [comment]
@Wing924 lack of tests/comments/logging is not a problem, the whole design is not stable for now. i feel it can be (much) better.  [Some parts](https://github.com/l2isbad/go.d.plugin/blob/master/internal/pkg/helpers/log/reader.go) looks ugly...

**Comment by Wing924** [comment]
I read the codes more than 5 times and realize the `internal/pkg/helpers/log` is not logging but  `LogService` in python plugin :smile:

**Comment by l2isbad** [comment]
Haha, this is one of the names that I do not like too :smile_cat: It must be changed 100%.
`tail` is perfect

If you willing please do a PR

**Comment by l2isbad** [comment]
> I read the codes more than 5 times

i will do it readable later, it was implemented a long time ago, my goal was to make it fast and memory usage friendly

**Comment by l2isbad** [comment]
I think we have agreed on getter/setter naming rule :+1:
