### ISSUE TITLE
Why do you fork the yaml?

### ISSUE THREAD

**Issue by Wing924** [l2isbad/go.d.plugin#5]
I want to know the difference between forked yaml and original one.

**Comment by l2isbad** [comment]
[field validation added](https://github.com/l2isbad/yaml/commit/aa9c5dfde78ee8088f1dc6a4b0b7c175ec35f863)
 (new field tags: `required`, `inrange`, `inregex(p|d)`)

```go
// inregexp returns error if not matches
// inregexd returns error if matches
type Example struct {
	Range    int    `yaml:"filed1,inrange:[1:10]"` // range:[:10] || range:[1:]
	Regexp   string `yaml:"field2,inregexp:REGULAR_EXPRESSION"`
	Required bool   `yaml:"field3,required"`
}

```

**Comment by Wing924** [comment]
If we really need this, how about send that PR to original one?
Use the forked library will much increase maintenance cost.

**Comment by l2isbad** [comment]
> If we really need this

Yes, we need this. It's a very nice feature. 

>  how about send that PR to original one?

Well, i think this is very specific changes which will not be accepted.

> Use the forked library will much increase maintenance cost.

How?

**Comment by Wing924** [comment]
I think this is what you want:
<https://github.com/go-playground/validator>

sample:
```go
// User contains user information
type User struct {
	FirstName      string     `validate:"required"`
	LastName       string     `validate:"required"`
	Age            uint8      `validate:"gte=0,lte=130"`
	Email          string     `validate:"required,email"`
	FavouriteColor string     `validate:"iscolor"`                // alias for 'hexcolor|rgb|rgba|hsl|hsla'
	Addresses      []*Address `validate:"required,dive,required"` // a person can have a home and cottage...
}
```

I suggest not use forked yaml and use standard yaml with validator instead.

**Comment by l2isbad** [comment]
This package is nice, looks like it is suitable for our needs. 
Give me some time to rewrite `validation` loginc

**Comment by l2isbad** [comment]
Ok, we are free from my `yaml` fork :smile:
