### ISSUE TITLE
LogService design

### ISSUE THREAD

**Issue by Wing924** [l2isbad/go.d.plugin#7]
1. Let's rename it to tail: <https://github.com/l2isbad/go.d.plugin/tree/master/internal/pkg/helpers/log>

2. How about use [hpcloud/tail](https://github.com/hpcloud/tail)?

**Comment by l2isbad** [comment]
1. Yes
2. I think no, why do we need external package when implementation is relatively simple (and already implemented and work nice)

**Comment by l2isbad** [comment]
About the design as a thing. I will make it more readable, it is not a problem at all.

**Comment by Wing924** [comment]
The `tail` looks simple but difficult. If we need performance, we can take advantage of OS method, such as `fsnotify` on linux. The hpcloud/tail package do all well for you.

**Comment by Wing924** [comment]
rename PR: #8
