### ISSUE TITLE
GetData should be map[string]interface{}

### ISSUE THREAD

**Issue by Wing924** [l2isbad/go.d.plugin#9]
https://github.com/l2isbad/go.d.plugin/blob/b0d058d4eccf17f988eb38f1675efbc2b0cb5443/internal/modules/module.go#L18

I'm try to write prometheus service and found `GetData()` returns `map[string]int64`. 
Because some metrics is `float64`, I can't make `map[string]int64`. Let's change it to `map[string]interface{}`.

**Comment by l2isbad** [comment]
Hm, workaround for floats is multiplying to 1000 in module and dividing to 1000 in charts.

**Comment by Wing924** [comment]
Why do you force to use int64?

**Comment by l2isbad** [comment]
From netdata's wiki:

> value
> 
> is the collected value, only integer values are collected. If you want to push fractional values, multiply this value by 100 or 1000 and set the DIMENSION divider to 1000.

**Comment by l2isbad** [comment]
https://github.com/firehol/netdata/wiki/External-Plugins

**Comment by Wing924** [comment]
understood

**Comment by l2isbad** [comment]
@Wing924 please read the whole `External Plugins` section, it will be useful for understanding how it works and why.
